DGP/src/DashGP/DashGPBundle/Entity/MonthlyPayform.php
<?php

namespace DashGP\DashGPBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use DashGP\DashGPBundle\Entity\PayformExtract;

/**
 * Payform
 *
 * @ORM\Table(name="dav_monthly_payform")
 * @ORM\Entity(repositoryClass="DashGP\DashGPBundle\Repository\MonthlyPayformRepository")
 */
class MonthlyPayform
{
    const STATUS_ACTIVE     = "ACTIVE";
    const STATUS_REPLACED   = "REPLACED";
    const STATUS_DELETED    = "DELETED";
    const STATUS_TODELETE   = "TO_DELETE";

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="eos_id", type="integer" , nullable=false)
     */
    private $eosId;

    /**
     * @var integer
     *
     * @ORM\Column(name="month", type="integer" , nullable=false)
     */
    private $month;

    /**
     * @var integer
     *
     * @ORM\Column(name="year", type="integer" , nullable=false)
     */
    private $year;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_submitted", type="datetime" , nullable=false)
     */
    private $dateSubmitted;

    /**
     * @var text
     *
     * @ORM\Column(name="file_title", type="text", nullable=false)
     */
    private $fileTitle;

    /**
     * @var text
     *
     * @ORM\Column(name="file_extension", type="text", nullable=false)
     */
    private $fileExtension;

    /**
     * @var text
     *
     * @ORM\Column(name="file_path", type="text", nullable=false)
     */
    private $filePath;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="boolean", nullable=false)
     */
    private $status;

    /**
     * @var string
     *
     * @ORM\Column(name="upload_status", type="string", nullable=false)
     */
    private $uploadStatus;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime" , nullable=false)
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime" , nullable=false)
     */
    private $updatedAt;

    /**
     * @var integer
     *
     * @ORM\Column(name="created_by", type="integer" , nullable=false)
     */
    private $createdBy;

    /**
     * @var PayformExtract $extract
     * @ORM\ManyToOne(targetEntity="DashGP\DashGPBundle\Entity\PayformExtract",  inversedBy="payforms", cascade={"persist", "merge"})
     * @ORM\JoinColumn(name="extract_id", nullable=true)
     */
    private $extract;

    /**
     * Get Title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->fileTitle;
    }

    /**
     * Get Extension
     *
     * @return string
     */
    public function getExtension()
    {
        return $this->fileExtension;
    }

    public function setTitle( $fileTitle )
    {
        $this->fileTitle = $fileTitle;
        return $this;
    }

    public function setExtension( $fileExtension )
    {
        $this->fileExtension = $fileExtension;
        return $this;
    }

    public function __construct()
    {
        $this->status       = true;
        $this->uploadStatus = MonthlyPayform::STATUS_ACTIVE; 
    }

    /**
     * get id
     *
     * @return integer id
     */
    public function getId(){
        return $this->id;
    }
    
    /**
     * get eos ID
     *
     * @return integer eosId
     */
    public function getEosId(){
        return $this->eosId;
    }

    /**
     * Set Eos ID
     *
     * @param integer $eosId
     * @return MonthlyPayform
     */
    public function setEosId( $eosId ){
        $this->eosId = $eosId;
        return $this;
    }

    /**
     * get month
     *
     * @return integer month
     */    
    public function getMonth(){
        return $this->month;
    }

    /**
     * Set Month
     *
     * @param integer $month
     * @return MonthlyPayform
     */
    public function setMonth( $month ){
        $this->month = $month;
        return $this;
    }

    /**
     * get year
     *
     * @return integer year
     */
    public function getYear(){
        return $this->year;
    }

    /**
     * Set Year
     *
     * @param integer $year
     * @return MonthlyPayform
     */
    public function setYear( $year ){
        $this->year = $year;
        return $this;
    }

    /**
     * get date submitted
     *
     * @return Datetime dateSubmitted
     */
    public function getDateSubmitted(){
        return $this->dateSubmitted;
    }

    /**
     * Set Date Submitted
     *
     * @param Datetime $dateSubmitted
     * @return MonthlyPayform
     */
    public function setDateSubmitted( $dateSubmitted ){
        $this->dateSubmitted = $dateSubmitted;
        return $this;

    }
    
    /**
     * get file Path
     *
     * @return text filePath
     */
    public function getFilePath(){
        return $this->filePath;
    }

    public function getPath()
    {
        return $this->filePath;
    }

    /**
     * Set File Path
     *
     * @param string $filePath
     * @return MonthlyPayform
     */
    public function setFilePath( $filePath ){
        $this->filePath = $filePath;
        return $this;
    }
    
    /**
     * get status
     *
     * @return string status
     */
    public function getStatus(){
        return $this->status;
    }

    /**
     * Set status
     *
     * @param string $status
     * @return MonthlyPayform
     */
    public function setStatus( $status ){
        $this->status = $status;
        return $this;
    }

    /**
     * get upload status
     *
     * @return string uploadStatus
     */
    public function getUploadStatus(){
        return $this->uploadStatus;
    }

    /**
     * Set uploadStatus
     *
     * @param string $uploadStatus
     * @return MonthlyPayform
     */
    public function setUploadStatus( $uploadStatus ){
        $this->uploadStatus = $uploadStatus;
        return $this;
    }

    /**
     * get Date created
     *
     * @return Datetime createdAt
     */
    public function getCreatedAt(){
        return $this->createdAt;
    }

    /**
     * Set Date created
     *
     * @param Datetime $createdAt
     * @return MonthlyPayform
     */
    public function setCreatedAt( $createdAt ){
        $this->createdAt = $createdAt;
        return $this;

    }

    /**
     * get date Updated
     *
     * @return Datetime updatedAt
     */
    public function getUpdatedAt(){
        return $this->updatedAt;
    }

    /**
     * Set Date Updated
     *
     * @param Datetime $updatedAt
     * @return MonthlyPayform
     */
    public function setUpdatedAt( $updatedAt ){
        $this->updatedAt = $updatedAt;
        return $this;
    }

    /**
     * get createdBy
     *
     * @return integer createdBy
     */
    public function getCreatedBy(){
        return $this->createdBy;
    }

    /**
     * Set createdBy
     *
     * @param integer $createdBy
     * @return MonthlyPayform
     */
    public function setCreatedBy( $createdBy ){
        $this->createdBy = $createdBy;
        return $this;
    }

    /**
     * get extract
     *
     * @return \DashGP\DashGPBundle\Entity\PayformExtract extract
     */
    public function getExtract(){
        return $this->extract;
    }

    /**
     * Set extract
     *
     * @param \DashGP\DashGPBundle\Entity\PayformExtract $extract
     * @return MonthlyPayform
     */
    public function setExtract( \DashGP\DashGPBundle\Entity\PayformExtract $extract ){
        $this->extract = $extract;
        return $this;
    }

    public function getMimeType(){
        return "application/pdf";
    }
}

DGP/src/DashGP/DashGPBundle/Controller/SignatureController.php
<?php
namespace DashGP\DashGPBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use DashGP\DashGPBundle\Entity\User;
use DashGP\DashGPBundle\Entity\Branch;
use DashGP\DashGPBundle\Entity\GenericManager;
use DashGP\DashGPBundle\Entity\Mission;
use DashGP\DashGPBundle\Form\FilesType;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\HttpFoundation\JsonResponse;

class SignatureController extends Controller
{
    public function indexAction($extranetId)
    {
        //http://localhost/Davidson/extranet/dgp_manager/app_dev.php/dashboardgp/%9A%CC%8A%B7%BBNz%C2%5BE%89%87%03k%B9%9B

        $decId = $extranetId;
        $r1 = substr($decId, 0, 3);
        $r2 = substr($decId, strlen($decId) - 2, 2);


        $num = substr($decId, 3, strlen($decId) - 5);
        if( $r2 == 0 )
            return new Response();
        $davId = ''. (($num / $r2) - $r1);
        
        $user = new User($this->container,$davId);
        $eosId = $user->getEosId();
        
        $branchQuery = $this->get('dashgp.eos_db')->getBranch($eosId);
        $branchQuery = $branchQuery[0];
        $branch = new Branch(
                $branchQuery['id'],
                $branchQuery['name'],
                $branchQuery['address'],
                $branchQuery['address_city'],
                $branchQuery['address_postalcode'],
                $branchQuery['address_country']);
        
        $userFirstName = $user->getFirstName();
        $userLastName = $user->getLastName();
        $matchMobile = '#^06#';
        
        if(preg_match($matchMobile , $user->getPhonePro() ) == true)
        {
            $user->setPhoneMobile($user->getPhonePro());
            $user->setPhonePro('');
        }
        if(preg_match($matchMobile , $user->getPhoneMobile() )!= true)
            $user->setPhoneMobile('');
        //die(var_dump($user->getPhonePro()));

        return $this->render('DashGPDashGPBundle:Signature:index.html.twig',array
            (
                'user'  => $user,
                'branch'=>$branch,
            ));
    }
    public function downloadAction($id)
    { 
        $request = $this->getRequest();
        
        $firstName = htmlentities($request->get('firstName'));
        $lastName = htmlentities($request->get('lastName'));
        $title = htmlentities($request->get('title'));
        $company = htmlentities($request->get('company'));
        $telephone = htmlentities($request->get('telephone'));
        $mobile = htmlentities($request->get('mobile'));
        $address = htmlentities($request->get('address'));
        $city = htmlentities($request->get('city'));
        $country = htmlentities($request->get('country'));
        $signToUse = htmlentities($request->get('signToUse'));
        $telOrMobile = htmlentities($request->get('telOrMobile'));
        

        $result = $this->get('dashgp.sign.ref')->getSignature($firstName,$lastName,$title,$company,$telephone,$mobile,$telOrMobile,$address,$city,$country,$signToUse);
        $result = $result;
        //die(var_dump($result));
        
        
        $response = new Response();
        $filename = "davidson_2015.htm";
        $fichier = "davidson_2015";
        $response->setContent($result);

        // the headers public attribute is a ResponseHeaderBag
        $response->headers->set('Content-Type', 'text/plain');
        $response->headers->set('Content-Disposition', 'attachment; filename='. $fichier.'.htm');

        return $response;
    }
}

DGP/src/DashGP/DashGPBundle/Resources/views/Signature/Blocks/form.html.twig
<div class="sign_information-block-inside">
    <form class="sign_form" id="infos">
        <p class="sign_information-block-title">INFORMATIONS</p>
            <div class="sign_label_container inlineBlock" >
                <label for="sign_firstName" class="sign_label ">
                Prénom *
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_firstName" class="sign_obligatoire sign_input inlineBlock" type="text" name="sign_firstName" value="{{ user.firstName }}">
            </div>
            
            <div class="sign_label_container inlineBlock" >
                <label for="sign_lastName" class="sign_label">
                    Nom *
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_lastName" class="sign_obligatoire sign_input" type="text" name="sign_lastName" value="{{ user.lastName }}">
            </div>
            
            <div class="sign_label_container inlineBlock" >
                <label for="sign_title" class="sign_label">
                    Fonction *
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_title" class="sign_obligatoire sign_input" type="text" name="sign_title" value="{{ user.jobTitle }}">
            </div>
            
            <div class="sign_label_container inlineBlock" >
                <label for="sign_company" class="sign_label">
                    Société *
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_company" class="sign_obligatoire sign_input" type="text" name="sign_company" value="{{ branch.name }}">
            </div>
            
            <div class="sign_label_container inlineBlock" >
                <label for="sign_telephone" class="sign_label">
                    Tel. Fixe
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_telephone" class="sign_input" type="text" name="sign_telephone" value=
                       "{% if branch.extension != '' and user.phonePro != '' %}{{ branch.extension ~ " " ~ user.phonePro|slice(1, 15) }}{% else %}{{ user.phonePro }}{% endif %}">
            </div>
            
            <div class="sign_label_container inlineBlock" >
                <label for="sign_mobile" class="sign_label">
                    Et/ou Mobile
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_mobile" class="sign_input" type="text" name="sign_mobile" value=
                       "{% if branch.extension != '' and user.phoneMobile != '' %}{{ branch.extension ~ " " ~ user.phoneMobile|slice(1, 15) }}{% else %}{{ user.phoneMobile }}{% endif %}">
            </div>
            
            <div class="sign_label_container inlineBlock" >
                <label for="sign_address" class="sign_label">
                    Adresse *
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_address" class="sign_obligatoire sign_input" type="text" name="sign_address" value="{{ branch.address }}">
            </div>
            
            <div class="sign_label_container inlineBlock" >
                <label for="sign_code" class="sign_label">
                    Code postal *
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_code" class="sign_input" type="text" name="sign_code" value="{{ branch.addressPostalcode  }}">
            </div>
            
            <div class="sign_label_container inlineBlock" >
                <label for="sign_city" class="sign_label">
                    Ville *
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_city" class="sign_obligatoire sign_input" type="text" name="sign_city" value="{{ branch.addressCity }}">
            </div>
            
            <div class="sign_label_container inlineBlock" >
                <label for="sign_country" class="sign_label">
                    Pays *
                </label>
            </div>
            <div class="inlineBlock sign_input_container">
                <input id="sign_country" class="sign_obligatoire sign_input" type="text" name="sign_country" value="{{ branch.addressCountry }}">
            </div>
            
            <input class="sign_submit sign_input" id="sign_submit" type="button" value="Valider">
    </form>
</div>

DGP/src/DashGP/DashGPBundle/Resources/views/Signature/Blocks/reference1.html.twig
<table cellpadding="0" cellspacing="0" style="width:430px;color:white;font-family:arial,sans-serif;background-color:#FFFFFF;">
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="vertical-align: bottom;font-size:15px;height:25px;min-width:200px;padding-left:5px;font-weight:bold" nowrap>
            <span id="sign_sign1_firstName"></span><span> </span><span id="sign_sign1_lastName"></span>
        </td>
        <td  rowspan="7" style="text-align: right;" bgcolor="#38b99a">
            <img alt="" style="width:149px;vertical-align:bottom;" src="https://extranet.davidson.fr/imagesSignature/h2.png"/>
                 </td>
        <td rowspan="7">
            <a target="_blank" href="http://www.davidson.fr/">
                <img alt="www.davidson.fr" style="width:136px;" src="https://extranet.davidson.fr/imagesSignature/logo+20px.png"/>
            </a>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="padding-left:5px;font-size:11px;font-style: italic;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign1_title"></span></font></span>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="vertical-align: top;height:25px;padding-left:5px;font-size:11px;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign1_company"></span></font></span>
        </td>
    </tr>

    <tr>
        <td id="sign_telToChooseTel" colspan="4" bgcolor="#38b99a" style="padding-left:5px;font-size:11px;text-decoration:none !important;" nowrap>
            <a id="sign_sign1_telephoneValue" style="text-decoration:none !important;" >
                <span style="color:white !important;"><font color="#FFFFFF" style="text-decoration:none !important;">Tel : </font></span>
                <span style="color:white !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign1_telephone"></span></font></span>
            </a>
        </td>
        <td id="sign_telToChooseMobile" colspan="4" bgcolor="#38b99a" style="padding-left:5px;font-size:11px;text-decoration:none !important;" nowrap>
            <a id="sign_sign1_mobileValue" style="text-decoration:none !important;" >
                <span style="color:white !important;"><font color="#FFFFFF" style="text-decoration:none !important;">Mobile : </font></span>
                <span style="color:white !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign1_mobile"></span></font></span>
            </a>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="padding-left:5px;font-size:11px;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign1_address"></span></font></span>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="vertical-align: top;padding-left:5px;font-size:11px;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign1_city"></span></font></span>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="vertical-align: top;height:20px;padding-left:5px;font-size:11px;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign1_country"></span></font></span>
        </td>
    </tr>
    <tr>
        <td style="width:200px;">
            <a target="-blank" href="http://www.davidson.fr/davidson/gptw/">
                <img alt="" style="vertical-align: middle;" src="https://extranet.davidson.fr/imagesSignature/bg.png"/>
            </a>
        </td>
        <td width="10">
            <a target="_blank" href="http://www.viadeo.com/v/company/davidson-consulting?ga_from=Fu:/general;Fb:quick-search-bar;Fe:company">
                <img alt="" style="vertical-align: middle;text-align:center;" src="https://extranet.davidson.fr/imagesSignature/btn1-02.png"/>
            </a>
        </td>
        <td width="10">
            <a target="_blank" href="http://www.facebook.com/Davidson.Consulting?ref=hl">
                <img alt="" style="vertical-align: middle;text-align:center;" src="https://extranet.davidson.fr/imagesSignature/btn2-02.png"/>
                     </td>
        <td width="10">
            <a target="_blank" href="http://www.linkedin.com/company/davidson-consulting?trk=tyah&trkInfo=tarId%3A1412581795508%2Ctas%3Adavidson%2Cidx%3A2-2-7">
                <img alt="" style="vertical-align: middle;text-align:center;" src="https://extranet.davidson.fr/imagesSignature/btn3-02.png"/>
            </a>
        </td>
        <td style="text-align: right;">
            <img alt="" style="width:38px;vertical-align:bottom;" src="https://extranet.davidson.fr/imagesSignature/b.png"/>
        </td>
        <td bgcolor="black" valign="middle" width="290" style="text-align:center;font-family:arial,sans-serif;font-size:12px;vertical:align;text-decoration:none !important;">
            <a href="http://www.davidson.fr" style="text-decoration:none !important;" >
                <span style="color:#a5143b !important;"><font color="#a5143b" style="text-decoration:none !important;">www.davidson.fr</font></span>
            </a>
        </td>
    </tr>
    <tr>
        <td colspan="6" align="center" style="vertical-align: bottom;height:15px;color:black;font-family:Arial,sans-serif;font-style: italic;font-size:7px;">Ensemble adoptons des gestes responsables : n'imprimez ce mail que si necessaire.</td>
    </tr>
</table>

DGP/src/DashGP/DashGPBundle/Resources/views/Signature/Blocks/reference2.html.twig
<table cellpadding="0" cellspacing="0" style="width:430px;color:white;font-family:arial,sans-serif;background-color:#FFFFFF;">
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="vertical-align: bottom;font-size:15px;height:25px;min-width:200px;padding-left:5px;font-weight:bold" nowrap>
            <span id="sign_sign2_firstName"></span><span> </span><span id="sign_sign2_lastName"></span>
        </td>
        <td  rowspan="8" style="text-align: right;" bgcolor="#38b99a">
            <img alt="" style="width:169px;vertical-align:bottom;" src="https://extranet.davidson.fr/imagesSignature/h2.png"/>
        </td>
        <td rowspan="8">
            <a target="_blank" href="http://www.davidson.fr/">
                <img alt="www.davidson.fr" style="width:154px;" src="https://extranet.davidson.fr/imagesSignature/logo+20px.png"/>
            </a>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="padding-left:5px;font-size:11px;font-style: italic;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign2_title"></span></font></span>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="vertical-align: top;height:25px;padding-left:5px;font-size:11px;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign2_company"></span></font></span>
        </td>
    </tr>

    <tr>
        <td colspan="4" bgcolor="#38b99a" style="padding-left:5px;font-size:11px;text-decoration:none !important;" nowrap>
            <a id="sign_sign2_telephoneValue" href="" style="text-decoration:none !important;" >
                <span style="color:white !important;"><font color="#FFFFFF" style="text-decoration:none !important;">Tel : </font></span>
                <span style="color:white !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign2_telephone"></span></font></span>
            </a>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="padding-left:5px;font-size:11px;text-decoration:none !important;" nowrap>
            <a id="sign_sign2_mobileValue" href="" style="text-decoration:none !important;" >
                <span style="color:white !important;"><font color="#FFFFFF" style="text-decoration:none !important;">Mobile : </font></span>
                <span style="color:white !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign2_mobile"></span></font></span>
            </a>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="padding-left:5px;font-size:11px;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign2_address"></span></font></span>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="vertical-align: top;padding-left:5px;font-size:11px;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign2_city"></span></font></span>
        </td>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#38b99a" style="vertical-align: top;height:20px;padding-left:5px;font-size:11px;" nowrap>
            <span style="color:white !important;text-decoration:none !important;"><font color="#FFFFFF" style="text-decoration:none !important;"><span id="sign_sign2_country"></span></font></span>
        </td>
    </tr>
    <tr>
        <td style="width:200px;">
            <a target="-blank" href="http://www.davidson.fr/davidson/gptw/">
                <img alt="" style="vertical-align: middle;" src="https://extranet.davidson.fr/imagesSignature/bg.png"/>
            </a>
        </td>
        <td width="10">
            <a target="_blank" href="http://www.viadeo.com/v/company/davidson-consulting?ga_from=Fu:/general;Fb:quick-search-bar;Fe:company">
                <img alt="" style="vertical-align: middle;text-align:center;" src="https://extranet.davidson.fr/imagesSignature/btn1-02.png"/>
            </a>
        </td>
        <td width="10">
            <a target="_blank" href="http://www.facebook.com/Davidson.Consulting?ref=hl">
                <img alt="" style="vertical-align: middle;text-align:center;" src="https://extranet.davidson.fr/imagesSignature/btn2-02.png"/>
            </a>
        </td>
        <td width="10">
            <a target="_blank" href="http://www.linkedin.com/company/davidson-consulting?trk=tyah&trkInfo=tarId%3A1412581795508%2Ctas%3Adavidson%2Cidx%3A2-2-7">
                <img alt="" style="vertical-align: middle;text-align:center;" src="https://extranet.davidson.fr/imagesSignature/btn3-02.png"/>
            </a>
        </td>
        <td style="text-align: right;">
            <img alt="" style="width:38px;vertical-align:bottom;" src="https://extranet.davidson.fr/imagesSignature/b.png"/>
        </td>
        <td bgcolor="black" valign="middle" width="290" style="text-align:center;font-family:arial,sans-serif;font-size:12px;vertical:align;text-decoration:none !important;">
            <a href="http://www.davidson.fr" style="text-decoration:none !important;" >
                <span style="color:#a5143b !important;"><font color="#a5143b" style="text-decoration:none !important;">www.davidson.fr</font></span>
            </a>
        </td>
    </tr>
    <tr>
        <td colspan="6" align="center" style="vertical-align: bottom;height:15px;color:black;font-family:Arial,sans-serif;font-style: italic;font-size:7px;">Ensemble adoptons des gestes responsables : n'imprimez ce mail que si necessaire.</td>
    </tr>
</table>

DGP/src/DashGP/DashGPBundle/Resources/views/Signature/Blocks/resultHtml.html.twig
    <p class="sign_html-block-title">HTML</p>
    <div id='sign_clipboard_button'></div>
    <div class="sign_html-block-inside_container">
        <textarea class="sign_html-block-inside" id="sign_html-block-inside"></textarea>
        {#<button id="signCopyButton">Copy to Clipboard</button>#}
        <p class="sign_html-instructions">Vous pouvez copier-coller ce code html dans votre client e-mail ou télécharger le fichier .html</p>

        <form method ="POST" action="{{ path('signature_download_ajax', {'id': user.id} ) }}">
            <input id="sign_hdnFirstName" name="firstName" type="hidden">
            <input id="sign_hdnLastName" name="lastName" type="hidden">
            <input id="sign_hdnTitle" name="title" type="hidden">
            <input id="sign_hdnCompany" name="company" type="hidden">
            <input id="sign_hdnTelephone" name="telephone" type="hidden">
            <input id="sign_hdnMobile" name="mobile" type="hidden">
            <input id="sign_hdnAddress" name="address" type="hidden">
            <input id="sign_hdnCode" name="code" type="hidden">
            <input id="sign_hdnCity" name="city" type="hidden">
            <input id="sign_hdnCountry" name="country" type="hidden">

            <input id="sign_hdnSignToUse" name="signToUse" type="hidden">
            <input id="sign_hdnTelOrMobile" name="telOrMobile" type="hidden">

            <input class="sign_download sign_input" id="sign_download" type="submit" value="Télécharger">
        </form>
    </div>